---
version: '3'
services:

# START SERVICE controlplane.base
  controlplane:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.controlplane.base:v2.0.6
    environment: [${CONTROLPLANE_BASE_ENVIRONMENT}]
    command: [${CONTROLPLANE_BASE_COMMAND}]
    volumes: ['/etc:/hostfs/etc:ro','/var/run/docker.sock:/var/run/docker.sock','controlplane_repos_${CONTECO_DC_GLOBAL_STACKNAMES}:/conteco/pwd']
    ports: []
    networks: []
    deploy:
      mode: ${CONTROLPLANE_BASE_DEPLOY_MODE}
      resources:
        limits:
          memory: '${CONTROLPLANE_BASE_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${CONTROLPLANE_BASE_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${CONTROLPLANE_BASE_COMPOSE_EXTENSIONS}
# END SERVICE controlplane.base

networks: {}
volumes: {controlplane_repos_${CONTECO_DC_GLOBAL_STACKNAMES}: { external: true }}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
